<?php
// Added by Evan, if it screws stuff up remove this
session_start();
include 'db-config.inc.php';
function connect(){
  //Opening up a connection to the databse
  $mysqli = new mysqli(DBHOST, DBUSER, DBPASSWORD, DB);
  if ($mysqli->connect_errno) {
      echo "Failed to connect to MySQL: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
  }
  return $mysqli;
}
// Function for the front page to dynamically update if a user is logged in
function welcomeBar() {
  if ($_SESSION['signed_in']) {
    echo '<p id="welcome">Welcome ' . $_SESSION['username'] . '.</p><br>';
  } else {
    echo '<p id="welcome">Welcome unknown user! Please <a href="/login.php">sign in</a> or <a href="/register.php">create an account.</a></p><br>';
  }
}

// Function for the footer on each page to dynamically update if a user is logged in
function footerBar() {
  if ($_SESSION['signed_in']) {
    echo "<a href='/'>Home</a>|<a href='/signout.php'>Sign Out</a>";
  } else {
    echo "<a href='/'>Home</a>|<a href='/login.php'>Login</a>|<a href='/register.php'>Register</a>";
  }
}

// Function for the sign in/out buttons on the nav bar to dynamically update if the user is logged in
function loginBar() {
  if($_SESSION['signed_in']) {
        echo '<a href="signout.php">Sign out</a>'.
        '<a href="account.php">Profile</a>';
      } else {
        echo '<a href="/register.php" id="register" draggable="false">Register</a>'
        . '<a href="/login.php" id="login" draggable="false">Login</a>';
      }
}
// Adds a new post to the database
function createPost() {
  $mysqli = connect();
  // Retrieves the topic id generated by MySQL
  $post_content = $_POST['content'];
  $post_topic = $_POST['title'];
  $post_by = $_SESSION['username'];
  $formComplete = false;
  if (empty($post_content) || empty($post_topic)) {
    echo "<br>Please fill out the form title and/or description.<br>";
  } else {
    $formComplete = true;
  }
  if ($formComplete === true) {
    $stmt = $mysqli->prepare('INSERT INTO posts (`post_content`, `post_date`, `post_topic`, `post_by`) VALUES (?, NOW(), ?, ?)');
    $stmt->bind_param('sss', $post_content, $post_topic, $post_by);
    $stmt->execute();
    $result = $stmt->get_result();
    header("Location: http://talkoforum.ngrok.io/introductions.php");
  } else {
    echo 'Could not prepare statement!';
    echo mysql_errno($mysqli) . ": " . mysql_error($mysqli) . "\n";
  }
}

function createReply() {
  $mysqli = connect();
  // Retrieves the topic id generated by MySQL
  $post_content = $_POST['reply-content'];
  $post_topic = $_POST['title'];
  $post_by = $_SESSION['username'];
    $stmt = $mysqli->prepare('INSERT INTO posts (`post_content`, `post_date`, `post_by`, `reply_to`) VALUES (?, NOW(), ?, ?)');
    $stmt->bind_param('ssi', $post_content, $post_by, $_GET['id']);
    $stmt->execute();
    $result = $stmt->get_result();
    // header("Location: http://talkoforum.ngrok.io/introductions.php");
    echo $stmt->error;
  // } else {
  //   echo 'Could not prepare statement!';
  //   echo mysql_errno($mysqli) . ": " . mysql_error($mysqli) . "\n";
  // }
}

function passwordUsername(){

  $mysqli = connect();

  //setting up variables for the username and password inputs
  $usern = $mysqli -> real_escape_string($_POST["user"]);
  $pass = $_POST["pass"];

  //The if statment checks if username and password is set.
  if(!empty($usern) && !empty($pass)){
      //This is setting up a sql statment then setting the username and password as strings.
      // $sql = "SELECT * FROM users";
      $sql = "SELECT * FROM users WHERE username LIKE ?";
      $stmt = $mysqli->prepare($sql);
      $stmt->bind_param("s", $usern);


      //It is now executing the statment with the user name and password and getting the result.
      $stmt->execute();
      $result = $stmt->get_result();
      echo $result == null;
      $hashPass = "";
      if ($row = $result->fetch_assoc()) {
          $hashPass = $row["password"];
        }
      $correct = password_verify($pass, $hashPass);

      $_SESSION['signed_in'] = false;
      if($correct) {
        $_SESSION['signed_in'] = true;
        $_SESSION['username'] = $usern;
          header("Location: http://talkoforum.ngrok.io/successlogin.php");
          exit();
      } else {
          print "<p style='color:red; font-size:13px; font-family:Museo Sans;'>USERNAME OR PASSWORD IS INCORRECT</p>";
      }
  }
}
?>
